### ISSUE TITLE
Error message for `GBParseFlagMissingValue` prints garbage

### ISSUE THREAD

**Issue by paynerc** [tomaz/GBCli#18]
I am using v1.1 from Cocoapods. When I don't specify a value for a required argument, I get 

```
Missing value for command line option ò·;Æˇ, try --help!
```

Looking into this, I see that you have fixed this issue 2 years ago, but haven't release a version to Cocoapods. Any chance that you could cut a release at some point with these latest fixes? Even a 1.1.1?

**Comment by tomaz** [comment]
Released 1.2.1 version to cocoapods! It also includes fix from #19.

I already had 1.2 version in place, but for some reason forgot to push it to cocoapods... Don't ask :) Anyway, thanks for pointing it out...

**Comment by paynerc** [comment]
Thank you!
