### ISSUE TITLE
If a required value argument isn't provided, shouldn't parseOptionsWithArguments:count: return NO?

### ISSUE THREAD

**Issue by paynerc** [tomaz/GBCli#19]
Maybe I am missing something, but I guess I expected that if a required parameter is not present that the parser would alert me of this issue (other than just writing the message to the console) so that I could terminate execution of the application immediately?

**Comment by tomaz** [comment]
Thanks for bringing it up, I'll check the code in the following days - it's been a while since I was in it :) I'll then update podspec from #18 as well!

**Comment by tomaz** [comment]
Fixed this - you were right, the method should return NO and it does so now! The fix is also included in latest podspec - see #18

**Comment by paynerc** [comment]
Thanks so much!
